[DIR]
#traindatasets
train_dir=./traindata/1_2.tfrecord
#model
model_dir=./model/1/
#reference data
fixed_dir=./reference/atlas.tif
#annotation data
ann_dir=./reference/atlas.tif
[Default]
mk=2
n_iter=100
subject_id='fixed_mask2_25'
debug=store_true